# Generated by Django 5.1.2 on 2024-10-10 22:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_alter_generos_id_alter_generos_table'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuariosprofile',
            name='fk_genero',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='api.generos'),
        ),
    ]
