# Generated by Django 5.1.2 on 2024-10-10 22:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_usuariosprofile_fk_genero'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usuariosprofile',
            name='fk_genero',
        ),
    ]
